### ISSUE TITLE
Upgrade dependency

### ISSUE THREAD

**Issue by hongquan** [M-o-a-T/moat-util#1]
I found that lastest `moat-mqtt` has supported `anyio` 4, but at the same time, `moat-mqtt` depends on `moat-util` which requires `anyio` 3, so I cannot upgrade to latest `moat-mqtt`.

Could you lift the requirements for `moat-util`?

**Comment by smurfix** [comment]
Meh. Sorry that I missed this. Uploading 0.43.2 to fix it.
